name: mathwizard
description: "Mathwizard is a math game for kids"
publish_to: "none"
version: 1.3.0

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.5.0
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: ComicSans
      fonts:
        - asset: assets/fonts/comicsans.ttf
