class Schools {
  final List<Map<String, String>> penangSchools = [
    {
      "code": "PBC3017",
      "name": "SJKC CHIN HWA (PANTAI ACHEH)",
    },
    {"code": "PBC3019", "name": "SJKC CHONG CHENG"},
    {"code": "PBC3020", "name": "SJKC CHONG TEIK"},
    {"code": "PBC3021", "name": "SJKC CHUNG SHAN"},
    {"code": "PBC3022", "name": "SJKC EOK HUA"},
    {"code": "PBC3023", "name": "SJKC POI ENG"},
    {"code": "PBC3018", "name": "SJKC PULAU BETONG"},
    {"code": "PBC3024", "name": "SJKC SACRED HEART"},
    {"code": "PBC3025", "name": "SJKC SIN MIN"},
    {"code": "PBC3026", "name": "SJKC TAR THONG"},
    {"code": "PBC3027", "name": "SJKC WEN KHAI"},
    {"code": "PBC3028", "name": "SJKC YANG CHENG"},
    {"code": "PBC3029", "name": "SJKC YEOK HUA"},
    {"code": "PBC3030", "name": "SJKC YU CHYE"},
    {"code": "PBD3031", "name": "SJKT BAYAN LEPAS"},
    {"code": "PBD3032", "name": "SJKT SUNGAI ARA"},
    {"code": "PBA3018", "name": "SK BALIK PULAU"},
    {"code": "PBA3001", "name": "SK BATU MAUNG"},
    {"code": "PBA3014", "name": "SK BAYAN BARU"},
    {"code": "PBA3002", "name": "SK BAYAN LEPAS"},
    {"code": "PBA3020", "name": "SK BAYAN LEPAS 2"},
    {"code": "PBA3003", "name": "SK GENTING"},
    {"code": "PBA3004", "name": "SK KONGSI"},
    {"code": "PBA3017", "name": "SK MUTIARA PERDANA"},
    {"code": "PBA3005", "name": "SK PERMATANG DAMAR LAUT"},
    {"code": "PBA3016", "name": "SK SERI BAYU"},
    {"code": "PBB3014", "name": "SK SERI PERMAI"},
    {"code": "PBA3015", "name": "SK SERI RELAU"},
    {"code": "PBA1010", "name": "SK SG NIBONG"},
    {"code": "PBB3016", "name": "SK ST GEORGE BALIK PULAU"},
    {"code": "PBA3007", "name": "SK SUNGAI ARA"},
    {"code": "PBA3019", "name": "SK SUNGAI BATU"},
    {"code": "PBA3008", "name": "SK SUNGAI KOROK"},
    {"code": "PBA3009", "name": "SK SUNGAI PINANG"},
    {"code": "PBA3010", "name": "SK SUNGAI RUSA"},
    {"code": "PBA3006", "name": "SK TS AWANG HAD SALLEH"},
    {"code": "PBA3011", "name": "SK TELOK BAHANG"},
    {"code": "PBA3012", "name": "SK TELOK KUMBAR"},
    {"code": "PBA3013", "name": "SK TITI TERAS"},
    {"code": "PBC2033", "name": "SJKC AIK KEOW"},
    {"code": "PBC2034", "name": "SJKC AIK KEOW"},
    {"code": "PBC2035", "name": "SJKC CHIN HWA"},
    {"code": "PBC2038", "name": "SJKC CHUNG HWA 1"},
    {"code": "PBC2039", "name": "SJKC CHUNG HWA 2"},
    {
      "code": "PBC2037",
      "name": "SJKC CHUNG HWA PUSAT",
    },
    {"code": "PBC2040", "name": "SJKC KAI CHEE"},
    {"code": "PBC2041", "name": "SJKC KUANG YU"},
    {"code": "PBC2042", "name": "SJKC KWANG HWA"},
    {"code": "PBC2043", "name": "SJKC LEE CHEE"},
    {"code": "PBC2044", "name": "SJKC LI HWA"},
    {"code": "PBC2045", "name": "SJKC MAH HUA"},
    {"code": "PBC2032", "name": "SJKC MAK MANDIN"},
    {"code": "PBC2046", "name": "SJKC NUNG MIN"},
    {"code": "PBC2036", "name": "SJKC PEI YU"},
    {"code": "PBC2047", "name": "SJKC SIN CHUNG"},
    {
      "code": "PBD2048",
      "name": "SJKT LDG MALAKOFF",
    },
    {
      "code": "PBD2049",
      "name": "SJKT LDG MAYFIELD",
    },
    {"code": "PBD2076", "name": "SJKT MAK MANDIN"},
    {"code": "PBD2050", "name": "SJKT PALANIANDY"},
    {"code": "PBA2001", "name": "SK ARA RENDANG"},
    {"code": "PBB2028", "name": "SK ASSUMPTION"},
    {"code": "PBA2002", "name": "SK BAGAN AJAM"},
    {"code": "PBA2003", "name": "SK BAGAN JERMAL"},
    {"code": "PBA2004", "name": "SK BAGAN TUAN KECHIL"},
    {"code": "PBA2034", "name": "SK BERTAM INDAH"},
    {"code": "PBA2038", "name": "SK BERTAM PERDANA"},
    {"code": "PBA2005", "name": "SK BUMBONG LIMA"},
    {"code": "PBB2029", "name": "SK CONVENT 1"},
    {"code": "PBA2039", "name": "SK DESA MURNI"},
    {"code": "PBB2031", "name": "SK HASHIM AWANG"},
    {"code": "PBA2007", "name": "SK KAMPONG TO BEDOR"},
    {"code": "PBA2028", "name": "SK KAMPUNG SELAMAT"},
    {"code": "PBA2033", "name": "SK KEPALA BATAS"},
    {"code": "PBA2008", "name": "SK KUALA MUDA"},
    {"code": "PBA2009", "name": "SK KUALA PERAI"},
    {"code": "PBA2011", "name": "SK LAHAR KEPAR"},
    {"code": "PBA2031", "name": "SK LAHAR YOOI"},
    {"code": "PBB2075", "name": "SK MAK MANDIN"},
    {"code": "PBA2006", "name": "SK MOHD SHAH"},
    {"code": "PBA2012", "name": "SK PADANG MENORA"},
    {"code": "PBA2013", "name": "SK PASIR GEBU"},
    {"code": "PBA2014", "name": "SK PAYA KELADI"},
    {"code": "PBA2015", "name": "SK PENAGA"},
    {"code": "PBA2036", "name": "SK PENAGA JAYA"},
    {"code": "PBA2032", "name": "SK PENGKALAN JAYA"},
    {"code": "PBA2016", "name": "SK PERMATANG BERTAM"},
    {"code": "PBA2017", "name": "SK PERMATANG BINJAI"},
    {"code": "PBA2018", "name": "SK PERMATANG BULOH"},
    {"code": "PBA2019", "name": "SK PERMATANG JANGGUS"},
    {"code": "PBA2020", "name": "SK PERMATANG SINTOK"},
    {"code": "PBA2021", "name": "SK PERMATANG TO JAYA"},
    {"code": "PBA2022", "name": "SK PINANG TUNGGAL"},
    {"code": "PBA2035", "name": "SK POKOK SENA"},
    {"code": "PBA2023", "name": "SK PULAU MERTAJAM"},
    {"code": "PBA2037", "name": "SK SERI GEMILANG"},
    {"code": "PBB2032", "name": "SK ST MARK"},
    {"code": "PBA2024", "name": "SK SUNGAI DUA"},
    {"code": "PBA2030", "name": "SK SUNGAI NYIOR"},
    {"code": "PBA2025", "name": "SK SUNGAI PUYU"},
    {"code": "PBA2029", "name": "SK TAMAN SENANGAN"},
    {"code": "PBA2026", "name": "SK TASEK GELUGOR"},
    {"code": "PBA2027", "name": "SK TELOK AYER TAWAR"},
    {"code": "PBC4013", "name": "SJKC BOON BENG"},
    {"code": "PBC4016", "name": "SJKC CHONG KUANG"},
    {"code": "PBC4017", "name": "SJKC KAMPUNG JAWI"},
    {
      "code": "PBC4015",
      "name": "SJKC KAMPUNG VALDOR",
    },
    {"code": "PBC4018", "name": "SJKC KENG KOON"},
    {"code": "PBC4019", "name": "SJKC PAI TEIK"},
    {"code": "PBC4021", "name": "SJKC YOK ENG"},
    {
      "code": "PBD4022",
      "name": "SJKT LADANG BATU KAWAN",
    },
    {"code": "PBD4026", "name": "SJKT LADANG JAWI"},
    {
      "code": "PBD4032",
      "name": "SJKT LADANG VALDOR",
    },
    {"code": "PBD4023", "name": "SJKT LDG BYRAM"},
    {
      "code": "PBD4025",
      "name": "SJKT LDG CHANGKAT",
    },
    {"code": "PBD4028", "name": "SJKT LDG KRIAN"},
    {"code": "PBD4029", "name": "SJKT LDG SEMPAH"},
    {
      "code": "PBD4031",
      "name": "SJKT LDG TRANSKRIAN",
    },
    {
      "code": "PBD4024",
      "name": "SJKT NIBONG TEBAL",
    },
    {
      "code": "PBD4034",
      "name": "SJKT SUNGAI BAKAP",
    },
    {
      "code": "PBD4030",
      "name": "SJKT TASEK PERMAI",
    },
    {"code": "PBA4020", "name": "SK BAKAP INDAH"},
    {"code": "PBA4019", "name": "SK BANDAR TASEK MUTIARA"},
    {"code": "PBA4017", "name": "SK BATU KAWAN"},
    {"code": "PBA4001", "name": "SK BKT TAMBUN"},
    {"code": "PBA4013", "name": "SK JAWI"},
    {"code": "PBA4002", "name": "SK KELEDANG JAYA"},
    {"code": "PBB4012", "name": "SK METHODIST"},
    {"code": "PBA4003", "name": "SK NIBONG TEBAL"},
    {"code": "PBA4004", "name": "SK PERMATANG TOK MAHAT"},
    {"code": "PBA4005", "name": "SK PULAU AMAN"},
    {"code": "PBA4015", "name": "SK SAUJANA INDAH"},
    {"code": "PBA4014", "name": "SK SERI SENTOSA"},
    {"code": "PBA4011", "name": "SK SERI TASEK"},
    {"code": "PBA4012", "name": "SK SG BAKAU"},
    {"code": "PBA4006", "name": "SK SUNGAI ACHEH"},
    {"code": "PBA4007", "name": "SK SUNGAI BAKAP"},
    {"code": "PBA4008", "name": "SK SUNGAI DURI"},
    {"code": "PBA4009", "name": "SK SUNGAI KECHIL"},
    {"code": "PBA4010", "name": "SK SUNGAI SETAR"},
    {"code": "PBA4016", "name": "SK TAMAN MERAK"},
    {"code": "PBA4018", "name": "SK TASEK PERMAI"},
    {
      "code": "PBC0036",
      "name": "SJKC BENG TEIK (PUSAT)",
    },
    {"code": "PBC2079", "name": "SJKC CHUNG HWA 3"},
    {"code": "PBC0026", "name": "SJKC JIT SIN 'A'"},
    {"code": "PBC0027", "name": "SJKC JIT SIN 'B'"},
    {"code": "PBC0028", "name": "SJKC KAY SIN"},
    {"code": "PBC0029", "name": "SJKC KEOW KUANG"},
    {
      "code": "PBC0024",
      "name": "SJKC KG. SG. LEMBU",
    },
    {"code": "PBC0030", "name": "SJKC KIM SEN"},
    {
      "code": "PBC0023",
      "name": "SJKC KUBANG SEMANG",
    },
    {"code": "PBC0031", "name": "SJKC LAY KEOW"},
    {"code": "PBC0032", "name": "SJKC PENG BIN"},
    {
      "code": "PBC0022",
      "name": "SJKC PERKAMPUNGAN BERAPIT",
    },
    {
      "code": "PBC0021",
      "name": "SJKC PERMATANG TINGGI",
    },
    {"code": "PBC0033", "name": "SJKC SENG KEOW"},
    {"code": "PBC0034", "name": "SJKC SIN YA"},
    {"code": "PBC0035", "name": "SJKC TRUE LIGHT"},
    {
      "code": "PBD0036",
      "name": "SJKT BKT MERTAJAM",
    },
    {"code": "PBD0038", "name": "SJKT LADANG PRYE"},
    {"code": "PBD0037", "name": "SJKT LDG ALMA"},
    {"code": "PBD0035", "name": "SJKT LDG JURU"},
    {"code": "PBD2080", "name": "SJKT PERAI"},
    {
      "code": "PBD0034",
      "name": "SJKT PERMATANG TINGGI",
    },
    {"code": "PBA0001", "name": "SK ALMA"},
    {"code": "PBA0023", "name": "SK ALMA JAYA"},
    {"code": "PBA0026", "name": "SK BANDAR BARU PERDA"},
    {"code": "PBA0021", "name": "SK BUKIT INDERA MUDA"},
    {"code": "PBA0022", "name": "SK BUKIT MINYAK"},
    {"code": "PBA0002", "name": "SK BUKIT TEH"},
    {"code": "PBB0018", "name": "SK CONVENT"},
    {"code": "PBA0003", "name": "SK GUAR PERAHU"},
    {"code": "PBA0005", "name": "SK JALAN BAHARU PERAI"},
    {"code": "PBA0006", "name": "SK JUARA"},
    {"code": "PBA0007", "name": "SK JURU"},
    {"code": "PBA0008", "name": "SK KEBUN SIREH"},
    {"code": "PBB0021", "name": "SK KG BARU"},
    {"code": "PBA0009", "name": "SK KHIR JOHARI"},
    {"code": "PBA0010", "name": "SK MACANG BUBOK"},
    {"code": "PBA0029", "name": "SK MACHANG BUBOK II"},
    {"code": "PBA0011", "name": "SK MENGKUANG"},
    {"code": "PBA0027", "name": "SK PAUH JAYA"},
    {"code": "PBA0024", "name": "SKPK ALMA"},
    {"code": "PBA0028", "name": "SK PERMAI INDAH"},
    {"code": "PBA0012", "name": "SK PERMATANG PASIR"},
    {"code": "PBA0013", "name": "SK PERMATANG PAUH"},
    {"code": "PBA0014", "name": "SK PERMATANG TOK KANDU"},
    {"code": "PBA0018", "name": "SK SEBERANG JAYA"},
    {"code": "PBA0019", "name": "SK SEBERANG JAYA 2"},
    {"code": "PBA0025", "name": "SK SERI IMPIAN"},
    {"code": "PBA0015", "name": "SK SERI PENANTI"},
    {"code": "PBB2078", "name": "SK ST MARK"},
    {"code": "PBB0019", "name": "SK STOWELL"},
    {"code": "PBA0016", "name": "SK SUNGAI RAMBAI"},
    {"code": "PBA0030", "name": "SK TAMAN IMPIAN"},
    {"code": "PBA0020", "name": "SK TAMAN INDERAWASIH"},
    {"code": "PBA0017", "name": "SK TANAH LIAT"},
    {"code": "PCT0002", "name": "SEKOLAH RENDAH ISLAM AL MASRIYAH"},
    {"code": "PBC1046", "name": "SJKC AIK HUA"},
    {
      "code": "PBC1048",
      "name": "SJKC BENG TEIK CAWANGAN",
    },
    {"code": "PBC1049", "name": "SJKC CHIAO NAN"},
    {
      "code": "PBC1051",
      "name": "SJKC CHUNG HWA CONFUCIAN 'A'",
    },
    {
      "code": "PBC1052",
      "name": "SJKC CHUNG HWA CONFUCIAN 'B'",
    },
    {
      "code": "PBC1053",
      "name": "SJKC CONVENT DATUK KERAMAT",
    },
    {"code": "PBC1054", "name": "SJKC ENG CHUAN"},
    {"code": "PBC1055", "name": "SJKC HAN CHIANG"},
    {"code": "PBC1056", "name": "SJKC HENG EE"},
    {"code": "PBC1081", "name": "SJKC HU YEW SEAH"},
    {"code": "PBC1057", "name": "SJKC HUN BIN"},
    {"code": "PBC1050", "name": "SJKC JELUTONG"},
    {"code": "PBC1058", "name": "SJKC KEONG HOE"},
    {"code": "PBC1059", "name": "SJKC KHENG TEAN"},
    {
      "code": "PBC1062",
      "name": "SJKC KONG MIN CAWANGAN KEDUA",
    },
    {
      "code": "PBC1061",
      "name": "SJKC KONG MIN CAWANGAN SATU",
    },
    {
      "code": "PBC1060",
      "name": "SJKC KONG MIN PUSAT",
    },
    {"code": "PBC1063", "name": "SJKC KWANG HWA"},
    {"code": "PBC1064", "name": "SJKC LI TEK 'A'"},
    {"code": "PBC1065", "name": "SJKC LI TEK 'B'"},
    {
      "code": "PBC1066",
      "name": "SJKC LI TEK CAWANGAN",
    },
    {"code": "PBC1067", "name": "SJKC MIN SIN"},
    {
      "code": "PBC1068",
      "name": "SJKC MOH GHEE (PUSAT)",
    },
    {
      "code": "PBC1069",
      "name": "SJKC MOH GHEE CAWANGAN",
    },
    {"code": "PBC1070", "name": "SJKC PAI CHAI"},
    {
      "code": "PBC1045",
      "name": "SJKC PEREMPUAN CHINA",
    },
    {"code": "PBC1071", "name": "SJKC PHEI SHIN"},
    {"code": "PBC1072", "name": "SJKC PHOR TAY"},
    {"code": "PBC1073", "name": "SJKC POAY WAH"},
    {"code": "PBC1044", "name": "SJKC SHANG WU"},
    {
      "code": "PBC1075",
      "name": "SJKC SHIH CHUNG CAWANGAN",
    },
    {
      "code": "PBC1074",
      "name": "SJKC SHIH CHUNG PUSAT",
    },
    {"code": "PBC1076", "name": "SJKC SIN KANG"},
    {"code": "PBC1077", "name": "SJKC SUM MIN"},
    {"code": "PBC1078", "name": "SJKC SUM SUN"},
    {"code": "PBC1079", "name": "SJKC TONG SIAN"},
    {"code": "PBC1080", "name": "SJKC UNION"},
    {"code": "PBD1082", "name": "SJKT AZAD"},
    {
      "code": "PBD1086",
      "name": "SJKT JALAN SUNGAI",
    },
    {"code": "PBD1084", "name": "SJKT RAJAJI"},
    {"code": "PBD1085", "name": "SJKT RAMAKRISHNA"},
    {
      "code": "PBD1088",
      "name": "SJKT SUBRAMANIYA BARATHEE",
    },
    {"code": "PBA1001", "name": "SK AYER ITAM"},
    {"code": "PBA1002", "name": "SK BATU FERINGGHI"},
    {"code": "PBB1014", "name": "SK BATU LANCHANG"},
    {"code": "PBA1017", "name": "SK BUKIT GAMBIR"},
    {"code": "PBB1023", "name": "SK BUKIT GELUGOR"},
    {"code": "PBB1015", "name": "SK CONVENT GREEN LANE"},
    {"code": "PBB1017", "name": "SK CONVENT LEBUH LIGHT"},
    {"code": "PBB1019", "name": "SK CONVENT PULAU TIKUS"},
    {"code": "PBA1003", "name": "SK DATO KRAMAT"},
    {"code": "PBB1021", "name": "SK FRANCIS LIGHT"},
    {"code": "PBB1024", "name": "SK HUTCHINGS"},
    {"code": "PBA1016", "name": "SK JALAN HAMILTON"},
    {"code": "PBB1030", "name": "SK JALAN RESIDENSI"},
    {"code": "PBA1005", "name": "SK JELUTONG"},
    {"code": "PBB1026", "name": "SK JELUTONG BARAT"},
    {"code": "PBA1014", "name": "SK MINDEN HEIGHT"},
    {"code": "PBB1039", "name": "SK PADANG TEMBAK"},
    {
      "code": "PBA1015",
      "name": "SKPK JALAN HUTTON",
    },
    {
      "code": "PBE1040",
      "name": "SKPK PERSEKUTUAN",
    },
    {"code": "PBB1025", "name": "SK PEREMPUAN ISLAND"},
    {"code": "PBB1032", "name": "SK PEREMPUAN METHODIST"},
    {"code": "PBB1033", "name": "SK PYKETT METHODIST"},
    {"code": "PBA1018", "name": "SK SERI INDAH"},
    {"code": "PBA1009", "name": "SK SG GELUGOR"},
    {"code": "PBB1013", "name": "SK SRI AMAN"},
    {"code": "PBA1008", "name": "SK SRI TANJUNG"},
    {"code": "PBB1034", "name": "SK ST XAVIER"},
    {"code": "PBB1035", "name": "SK ST XAVIER CAWANGAN"},
    {"code": "PBA1006", "name": "SK TAN SRI P.RAMLEE"},
    {"code": "PBA1012", "name": "SK TANJONG TOKONG"},
    {"code": "PBA1011", "name": "SK TANJUNG BUNGA"},
    {"code": "PBB1037", "name": "SK WELLESLEY"},
  ];

  List<Map<String, String>> sarawakSchools = [
    {"code": "SK001", "name": "SK St Mary, Kuching"},
    {"code": "SK002", "name": "SK St Thomas, Kuching"},
    {"code": "SK003", "name": "SK St Joseph, Miri"},
    {"code": "SK004", "name": "SK Methodist, Sibu"},
    {"code": "SK005", "name": "SK Chung Hua, Bintulu"},
    {"code": "SK006", "name": "SK Merbau, Miri"},
    {"code": "SK007", "name": "SK Sg Plan, Bintulu"},
    {"code": "SK008", "name": "SK Nanga Oya, Kapit"},
    {"code": "SK009", "name": "SK Sibu Jaya, Sibu"},
    {"code": "SK010", "name": "SK Petra Jaya, Kuching"},
    {"code": "SK011", "name": "SK Siol Kanan, Kuching"},
    {"code": "SK012", "name": "SK Pujut Corner, Miri"},
    {"code": "SK013", "name": "SK Ulu Sebuyau, Samarahan"},
    {"code": "SK014", "name": "SK Matang Jaya, Kuching"},
    {"code": "SK015", "name": "SK Tanjung Batu, Bintulu"},
    {"code": "SK016", "name": "SK Lutong, Miri"},
    {"code": "SK017", "name": "SK Kidurong, Bintulu"},
    {"code": "SK018", "name": "SK Pujut, Miri"},
    {"code": "SK019", "name": "SK Sebauh, Bintulu"},
    {"code": "SK020", "name": "SK Agama Sibu, Sibu"},
    {"code": "SK021", "name": "SK Batu Lintang, Kuching"},
    {"code": "SK022", "name": "SK Jalan Arang, Kuching"},
    {"code": "SK023", "name": "SK Kampung Baru, Samarahan"},
    {"code": "SK024", "name": "SK Tabuan Jaya, Kuching"},
    {"code": "SK025", "name": "SK Lundu, Lundu"},
    {"code": "SK026", "name": "SK Bau, Bau"},
    {"code": "SK027", "name": "SK Serian, Serian"},
    {"code": "SK028", "name": "SK Padawan, Kuching"},
    {"code": "SK029", "name": "SK Asajaya, Samarahan"},
    {"code": "SK030", "name": "SK Sri Aman, Sri Aman"},
  ];
}
